### ISSUE TITLE
500 on a container that doesn't exist

### ISSUE THREAD

**Issue by jaxoncreed** [manomayam/manas#24]
When sending a request to a container that doesn't exist, the server gives a 500 error:

```
ERROR manas_storage::service::method::common::snippet::status_token: Unknown io error in resolving resource status token. Error:
  - Unknown io error. - Unexpected (temporary) at stat, context: { service: fs, path: demo-react/.__altcontent } => not a directory, source: Not a directory (os error 20)
```

This request results in the 500 error:

```
curl 'http://localhost:3001/demo-react/' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: http://localhost:3000/' -H 'authorization: DPoP ey.........' -H 'dpop: ey.....' -H 'Origin: http://localhost:3000' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site'
```

**Comment by damooo** [comment]
Thanks for reporting. OpenDAL recently made breaking changes to their api. Thus the issue. Should fix it.

**Comment by damooo** [comment]
Hello @jaxoncreed Though i tried many times, i couldn't reproduce the issue. I am properly getting 404. Is it reproducible on your machine? Could you provide some additional log (possible running with `-d` flag for debug.), Andalsopost `tree` of your root folder?.

Sorry for the inconvenience. Integration of complete test suite is work in progress. Till then request to tolerate. And also if possible, can you create a discussion, and share what all affordances you as an app developer want to see in Manas?

Thanks a lot.

**Comment by jaxoncreed** [comment]
Huh, For some reason, I'm not getting the error anymore. Perhaps it's a false alarm. 

Sure, I'll make a new issue and say all I'm looking for in Manas.
