### ISSUE TITLE
document type `application/sparql-update` not supported

### ISSUE THREAD

**Issue by hexagon6** [manomayam/manas#36]
When using my solid app (which uses "[@inrupt/solid-client](https://npmjs.com/package/@inrupt/solid-client)": "[^1.27.0](https://npmjs.com/package/@inrupt/solid-client)"), it updates an existing document.

This generates a xhr PATCH request with a `application/sparql-update` document-type (not n3)

Request:

`PATCH https://server/manas [HTTP/2 415  47ms]`
```sparql
INSERT DATA {<https://server/manas#e9e7822a-1d27-4c91-919c-redacted> a <https://www.w3.org/2002/12/cal/ical#Vtodo>;
<http://schema.org/text> "cross compile manas";
<https://www.w3.org/2002/12/cal/ical#created> "2023-11-15T04:55:12.899Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.};
```

Response:

```json
{"type":"https://httpstatuses.com/415","status":415,"title":"Unsupported Media Type","detail":"Unsupported patch document type."}
```

Server log:

```log
  2023-11-15T04:55:09.083794Z ERROR manas_repo_layers::patching::patcher::impl_::solid_insert_delete_patcher: Patch doc content type is not that of n3.
    at crates/manas_repo_layers/src/patching/patcher/impl_/solid_insert_delete_patcher.rs:177
    in manas_storage::service::method::put_or_patch::base::resolve_rep_patcher
    in manas_storage::service::method::put_or_patch::base::apply
    in manas_podverse::pod::service::impl_::storage_describing::StorageDescribingPodService::call
    in manas_podverse::podset::service::impl_::basic::BasicPodSetService::call
    in manas_authentication::challenge_response_framework::service::HttpCRAuthenticationService::call

  2023-11-15T04:55:09.084473Z ERROR manas_storage::service::method::put_or_patch::base: Error in resolving rep patcher.
    at crates/manas_storage/src/service/method/put_or_patch/base/mod.rs:715
    in manas_storage::service::method::put_or_patch::base::resolve_rep_patcher
    in manas_storage::service::method::put_or_patch::base::apply
    in manas_podverse::pod::service::impl_::storage_describing::StorageDescribingPodService::call
    in manas_podverse::podset::service::impl_::basic::BasicPodSetService::call
    in manas_authentication::challenge_response_framework::service::HttpCRAuthenticationService::call

```

**Comment by damooo** [comment]
Solid protocol only specifies `text/n3` n3-solid-insert-delete-patch. Sparql update was it's previous recommondation, but not now. Unfortunately, few libs and apps still use sparql-update.

Manas will not be supporting it anytime soon, as sparql parsers will be complex and big. Instead those apps must move over to be compatible with current spec.

This is already in works, we are working with rdflib.js [to merge n3-patch support](https://github.com/linkeddata/rdflib.js/pull/624).

**Comment by hexagon6** [comment]
Great! Thank you for the support and clarification.

**Comment by hexagon6** [comment]
Reference for later: https://github.com/inrupt/solid-client-js/blob/2366f8b3041248e8f620325e9646568981c92d3b/src/resource/solidDataset.ts#L365 this should change at some point for solid-client-js to be spec-compliant.
