### ISSUE TITLE
Instructions unclear on how to start the Solid Server.

### ISSUE THREAD

**Issue by argahsuknesib** [manomayam/manas#54]
Hello,

I wish to install the Manas solid server for my experiments, but I am not clear on how should I start? Should I use the manas all inclusive crate, but if I wish to disable some features/enable some such as the authentication, how do I do that?

I think it would be a good idea to have a startup guide in the readme as well as in the book [here](https://manomayam.github.io/manas/)

**Comment by damooo** [comment]
Hello @argahsuknesib 

Yes. The getting started guide will be added soon. Sorry for the delay in getting things done.

> I wish to install the Manas solid server for my experiments, but I am not clear on how should I start

We have to "[wireup](https://manomayam.github.io/manas/architecture.html#wiring-up-the-recipe)" the server recipe ourselves with chosen requirements, and then compile The wiring-up in rust is an easy job, but requires little documentation from my part. 

But for now few default server recipes are assembled at [manas_server](https://github.com/manomayam/manas/tree/main/crates/manas_server) crate. You may build those recipes for use now. For custom wireup, this crate can be used as a template.

```sh
cargo build --release --bin manas_server_single_fs_wac
```

The above command should build the default recipe with fs backend, wac access control, single pod providing server.

You can then run the built binary with a config file. Instructions are provided at [usage-section](https://github.com/manomayam/manas/tree/main/crates/manas_server/recipes/single_fs_wac#usage).

**Comment by argahsuknesib** [comment]
Hello, thanks for your reply. I will use it.
