### ISSUE TITLE
The server rejects the connection when doing a POST request to the server.

### ISSUE THREAD

**Issue by argahsuknesib** [manomayam/manas#56]
Hello,

I setup the server with file backend, and the server is running as I can do a curl request to get,
```bash
<http://localhost:3001/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/ldp#BasicContainer> .
<http://localhost:3001/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/ldp#Container> .
<http://localhost:3001/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/ldp#Resource> .
<http://localhost:3001/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/pim/space#Storage> .
<http://localhost:3001/> <http://www.w3.org/ns/solid/terms#owner> <https://argahsuknesib.github.io/me/> .
```
However, the server is rejecting the POST request I am doing to the server. The expected behaviour should be to create a file with the content of the variable.
What do you think that could be wrong?

```ts
    let communication = new LDPCommunication();
    let store_string = `
    <http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/spo2/#EventStream> <https://w3id.org/tree#member> <https://dahcc.idlab.ugent.be/Protego/_participant1/obs222> .
    <http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/spo2/#EventStream> <https://w3id.org/tree#member> <https://dahcc.idlab.ugent.be/Protego/_participant1/obs224> .
    <http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/spo2/#EventStream> <https://w3id.org/tree#member> <https://dahcc.idlab.ugent.be/Protego/_participant1/obs225> .
    <http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/spo2/#EventStream> <https://w3id.org/tree#member> <https://dahcc.idlab.ugent.be/Protego/_participant1/obs226> .
    <http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/spo2/#EventStream> <https://w3id.org/tree#member> <https://dahcc.idlab.ugent.be/Protego/_participant1/obs227> .
    <http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/spo2/#EventStream> <https://w3id.org/tree#member> <https://dahcc.idlab.ugent.be/Protego/_participant1/obs228> .
    <http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/spo2/#EventStream> <https://w3id.org/tree#member> <https://dahcc.idlab.ugent.be/Protego/_participant1/obs229> .
    <http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/spo2/#EventStream> <https://w3id.org/tree#member> <https://dahcc.idlab.ugent.be/Protego/_participant1/obs90> .
    <http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/spo2/#EventStream> <https://w3id.org/tree#member> <https://dahcc.idlab.ugent.be/Protego/_participant1/obs91> .
    <http://n061-14a.wall2.ilabt.iminds.be:3000/participant6/spo2/#EventStream> <https://w3id.org/tree#member> <https://dahcc.idlab.ugent.be/Protego/_participant1/obs92> .    `
    let headers = new Headers({ 'Content-type': 'text/turtle' });

    try {
        communication.post('http://localhost:3001/', store_string, headers).then((response) => {
            console.log(response.status);
        })
    } catch (error) {
        console.log(`The error is: ${error}`);
    }
```  
for which I get an error as,
```bash
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED ::1:3001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3001
  }
}
```
 
Note: LDPCommunication() is a part of the versionawareldesinldp package, and can be downloaded with 
`npm i @treecg/versionawareldesinldp`

**Comment by damooo** [comment]
Hello, did you built the server from source? Could you provide the binary if possible? Is it working with simple fetch? he error is regarding connection. Can you also paste your config.toml? Thanks for your feedback.

**Comment by damooo** [comment]
Once you run cargo build, it would create binaries in `target/debug/` or `target/release` folders with names `manas_server_single_fs_wac` etc. 
Better, i will release new binaries in github releases, and point you to them.

> does manas support SPARQL update
sparql update was old requirement. Solid protocol now requires to use n3-patch for patching rdf resources. Manas fully supports n3-patch.

> Is it multithreaded by default
Yes. It uses tokio's multithreaded runtime.

> if you ever ran a benchmark on how many succcesful GET requests the server is able to handle per second?

There is a lo of work going on regarding improving tests, adding benchmarks, implementing dynamic multi pod provisioning, docs etc. These all will take sometime. But project will be highly active wfrom with in few days.

**Comment by damooo** [comment]
I released [v0.1.1](https://github.com/manomayam/manas/releases/tag/v0.1.1) binaries. Please download the tarball, it contains the binary and instructions. You can test with that.

**Comment by argahsuknesib** [comment]
Thanks a lot @damooo! I will check it out.

**Comment by argahsuknesib** [comment]
Hello @damooo , it works for postman to for testing. However, I get a 401 unauthorized error. For which I think the DPoP header is missing. Is there a way I can config the server for development to remove the authentication all together?

**Comment by damooo** [comment]
Yes. We should assemble a recipe without authentication and access control. I can create one and add to releases if you require.

**Comment by argahsuknesib** [comment]
> Yes. We should assemble a recipe without authentication and access control. I can create one and add to releases if you require.

Thanks! That would be very helpful.

**Comment by damooo** [comment]
@argahsuknesib 

I released [v0.1.2](https://github.com/manomayam/manas/releases/tag/v0.1.2), it includes binaries with "noauth" string, which works without authn/acl. I didn't tested though.

Binaries are also shipped with s3 backend, if required.

**Comment by argahsuknesib** [comment]
Hello @damooo,

Thanks for the binaries. The server works pretty fast, as expected which is great. :)
However, I still have the simple issue of not being able to connect to the server to do a GET request with a script. I expect if there is a CORS issue or a firewall issue going on maybe?

The following script doesn't work when doing a GET request to the pod,
```
import axios from "axios";

async function test() {
    let headersList = {
     "Accept": "*/*",
     "User-Agent": "Kush"
    }
    
    let reqOptions = {
      url: "http://localhost:3001/",
      method: "GET",
      headers: headersList,
    }
    
    let response = await axios.request(reqOptions);
}

test();
```
However doing a GET request with a curl or postman  works flawlessly. 
Thanks!

**Comment by damooo** [comment]
> Thanks for the binaries. The server works pretty fast

Note that, response times are also heavily depends on the backend. s3 backend will be much efficient, as it only needs to do single ipc for contained resource metadata for containers, where as for fs backend it is O(n), n being number of contained resources.

>  However, I still have the simple issue of not being able to connect to the server to do a GET request with a script. I expect if there is a CORS issue or a firewall issue going on maybe?

CORS constrains applies only in browsers. Also Manas should handle that properly. I will check once with the provided script.

**Comment by damooo** [comment]
> `test()`
`await test()`
---------

Things works for me fine. Most probably your node process has issues with resolving "localhost".  You may have to check the host file config. It may work, if you set 127.0.0.1 to a custom host in hostsfile, and use that as server address.

See also: https://stackoverflow.com/questions/10643965/econnrefused-error-with-node-js-that-does-not-occur-in-other-clients

**Comment by argahsuknesib** [comment]
Thanks a lot for the help! I will check it out.

**Comment by damooo** [comment]
Great @argahsuknesib .

Please note that, the rdf data stored in or retrieved from the pod will contain the server address as part of resource uris. So it is best practice to set it to a permenant address. For testing not an issue.

I will close the issue for now. Please continue or open other, if you face any kind of issue or problem. You can also use github-discussions for general feedback and help. Feedback is much appreciated.

**Comment by damooo** [comment]
>  works with just substituting localhost with 127.0.0.1 eventhough my /etc/hosts is correct.

what is the version of node?

**Comment by argahsuknesib** [comment]
it is v18.16.0

**Comment by damooo** [comment]
If it works with curl and browser, then issue may be mostly with your system components. Try with some simple python script, if it works there.
