### ISSUE TITLE
Support for Solid Notifications Protocol or other notification mechanism.

### ISSUE THREAD

**Issue by argahsuknesib** [manomayam/manas#59]
Hello, I wish to monitor if new resources are added to a particular LDP container. Is this currently possible? If not, how do you think this should be solved? [CSS](https://github.com/CommunitySolidServer/CommunitySolidServer) uses Solid Notifications Protocol, to support websockets in single threaded mode and webhooks for multithreaded. There are also other notifications protocols such as, [SolidPREP](https://github.com/CxRes/solid-prep) and [StreamingHTTPChannel](https://solid.github.io/notifications/streaming-http-channel-2023).

**Comment by damooo** [comment]
Sorry for so late a response @argahsuknesib , due to a major health issue.

It is duplicate of #8 . Will be worked upon. Please give any suggestions at the issue.

Thank you.

**Comment by argahsuknesib** [comment]
Great to hear that you are well again. :)
